---
title: "Condatis Workshop Programme"
author: "Jenny Hodgson" 
date: '`r format(Sys.time(), "%B, %Y")`'

output:
  html_document: 
    collapsed: false
    theme: journal
    highlight: kate
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false
  github_document:
    toc: yes
    toc_depth: 4
    html_preview: TRUE

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Schedule

### Session 1

 - 11:20 — 11:45 Introduction to Condatis
 - 11:45 — 12:00 Web App tour 
 - 12:00 — 12:40 Exercises and Q&A
 - 12:00 — 12:50 Condatis Bottlenecks
 
### Session 2

 - 14:50 — 15:50 Condatis Exercise in R
 - 15:50 — 16:10 Explore Condatis Outputs in GIS
 - 16:10 — 16:25 Q&A 
 - 16:25 — 16:50 Potential application in your research

## Activities summary and material

### Session 1. Condatis Web App

_Introduction to Condatis_

descritption slides(link)

_Prioritisation in Borneo_

In this exercise we will use  [Condatis Web App](https://pgb.liv.ac.uk/~condatis_dev/) to ...

Download the data for this exercise [here](https://github.com/condatis/Ctraining_inR_25/tree/main) (update link to final version)


### Session 2. Condatis R

_Wetland connectivity in Eastern England_

In this exercise we will use R to explore the occurrence of bottlenecks for the wetlands in the east of England.

Download the data for this exercise here (update link to final version)

You can explore the outputs in this [QGIS project](https://github.com/condatis/Ctraining_inR_25/tree/main/R%20Example/QGIS_project) (update), by opening the *Condatis_Wetland_East.qgz* in QGIS, or load the layers in your preferred GIS software.


