---
title: "Workflow for Condatis in R"
author: "Jenny Hodgson" 
date: '`r format(Sys.time(), "%B, %Y")`'

output:
  html_document: 
    collapsed: false
    theme: flatly
    highlight: kate
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false
  github_document:
    toc: yes
    toc_depth: 4
    html_preview: TRUE

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, tidy = TRUE) 
```


This is an example of how to use Condatis in R

```{r eval=FALSE}

#Load necessary packages

library(sf)
library(terra)
library(sfheaders)
library(dplyr)
library(viridis)
```

## Data

### Habitat 

Read in habitat raster data and extract the raster properties


```{r eghab, echo=FALSE}
library(terra)

eghab = rast("data/wetland_east.tif")

plot(eghab)
```

```{r habitat, eval=FALSE}
eghab = rast("data/wetland_east.tif")

# Obtain Coordinate Reference System (crs) and extent (ext)
regextent = ext(eghab)
mycrs = crs(eghab)
myres = res(eghab)
unitcheck = linearUnits(eghab)
```
### Sources and targets

Source and target raster description

```{r ST, eval=FALSE}
direction = rast("east_W_E.tif")

```

```{r STplot, echo=FALSE}
library(terra)

eghab = rast("data/wetland_east.tif")
direction = rast("data/east_W_E.tif")
plot(eghab, legend = FALSE)
plot(direction, add=TRUE)
```

## Convert Rasters to points

