---
title: "Condatis in R 2025 (Ctraining_inR_25) Workshop Programme (updated 2026)"
author: "Jenny Hodgson" 
date: '`r format(Sys.time(), "%B, %Y")`'

output:
  html_document: 
    collapsed: false
    theme: journal
    highlight: kate
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: false
  github_document:
    toc: yes
    toc_depth: 4
    html_preview: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Schedule

### Session 1

-   09:00 Introduction to Condatis
-   09:15 Web App tour and explaining the Sabah exercise
-   09:30 Sabah exercise running, viewing outputs in GIS, with help as needed
-   10:20 Condatis Bottlenecks introductory presentation
-   10:30 Break

### Session 2

-   11:00 Condatis Bottlenecks Eastern England exercise in R
-   11:50 Recap; Q&A and requests; feedback survey
-   12:10 According to requests, either explore Condatis outputs further in GIS, or discuss applications for your own work

## Housekeeping for the training in Microsoft Teams, 2026

-   We have different experience levels but we are all here to learn. All questions are worth asking. You are encouraged to help each other.

-   Please mute your mic whenever not speaking, to avoid noise.

-   Please place short questions in the chat feed. You can elaborate on them verbally when useful.

-   If you lose your connection to Teams you can email Ricardo (he emailed you the Teams link recently)

-   We have a breakout room for 1:1 help with Georgia

## Links to materials[^1]

[^1]: Please note that we are making this code and documentation available under a GPL license; for more details see the LICENSE file. Copyright Jenny Hodgson and Claudia Gutierrez-Arellano 2025 unless otherwise stated (e.g. datasets). Please cite this archive as Jenny Hodgson and Claudia Gutierrez-Arellano (2025) Condatis connectivity analysis to plan resilient habitat networks - Condatis training in R. Available at: <https://github.com/condatis/Ctraining_inR_25>

### Finding the data

Data for both our exercises are included in a Github repository. It is simplest to download the whole repository [here](https://github.com/condatis/Ctraining_inR_25/tree/main)

Also, download Jenny's training presentation slides with introduction to Condatis and both exercises ([Condatis-training-slides-2026.pdf](https://condatis.github.io/Ctraining_inR_25/Condatis-training-slides-2026.pdf))

### Session 1. Condatis Web App materials

This quick reference document for the Sabah exercise summarises the steps you take (complementing the longer explanation which is in the training slides) ([Web_app_quick_reference.pdf](https://condatis.github.io/Ctraining_inR_25/Web_app_quick_reference.pdf))

Direct link to the [Condatis Web App](https://webapp.condatis.org.uk)

Read the full [web app help documentation](https://webapp.condatis.org.uk/help/help.html)

### Session 2. Condatis in R materials

*Wetland connectivity in Eastern England*

In this exercise we will use R to explore the occurrence of bottlenecks for the wetlands in the east of England. You will basically need the [full instructions in the workflow](https://condatis.github.io/Ctraining_inR_25/rworkflow). This is complemented by slides no. 46-55 in the training slides.

You can explore the outputs in your preferred GIS software.

## Session summary - Condatis connectivity analysis to plan resilient habitat networks

Condatis is decision support software to identify the best locations for habitat restoration to increase connectivity across landscapes. It can help planners to find multiple-win solutions for land management, so that biodiversity can recover and natural ecosystems can co-exist with human activities. Condatis’s metric of long-distance connectivity is particularly relevant under climate change, ensuring that networks of habitat facilitate range shifts. Condatis:

1.  Highlights pathways across a landscape that allow both dispersal and reproduction of species;

2.  Pinpoints bottlenecks in the habitat network, where there are restricted opportunities for colonisation, and where restoration would be most impactful;

3.  Ranks the feasible sites for habitat restoration, to efficiently enhance the existing habitat network.

Condatis has been developed since 2015 and has been used by conservation practitioners around the world, via its web application ([www.condatis.org.uk](https://www.condatis.org.uk)). Through collaboration with users, we have designed it to be fast and user-friendly, and to work with the kind of data that organisations typically have. This workshop will provide a brief overview of the software and a series of graded exercises, showcasing the different functions of Condatis.

## Background requirements

There will be examples using the Condatis web app as well as the R environment. Attendees will need some familiarity with GIS, e.g. reading, writing and querying raster data. You may use your own favoured GIS software or spatial package to view our input and output data, either R, ArcGIS Pro or QGIS. It may be advisable to update your GIS package to the latest version. We will not be offering in-depth GIS help during the session. R is essential for one of our exercises (for the analysis and not just for its GIS capability). Please install R version 4.3 or later before you start, and install the packages terra, sf, sfheaders, tidyverse and viridis. Before using the Condatis web app, you need to create a user account for yourself at <https://webapp.condatis.org.uk>.
